animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platyus']
print animals
print animals[1]
print animals[3-1]
print animals[1-1]
print animals[3]
print animals[5-1]
print animals[2]
print animals[6-1]
print animals[4]
